CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    created_on NUMERIC NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_on NUMERIC NOT NULL DEFAULT CURRENT_TIMESTAMP
);